from bext import goto
from time import sleep
from interface import Visual
from datetime import datetime
from keyboard import press_and_release


class Time:
    switch = False

    @classmethod
    def breaker(cls):
        input()
        cls.switch = True
        press_and_release('enter')

    @classmethod
    def runner(cls):
        cls.switch = False

    def coordsofnumber(self, value, xone, xtwo, xthree):
        self.graphicnumber(value[0], xone, xthree)
        self.graphicnumber(value[1], xtwo, xthree)

    def commandtime(self):
        if Visual().widthread == 120 and Visual().heightread == 30:
            coords = (85, 101, 45, 61, 5, 21, 10)
        else:
            coords = (
                int(Visual().widthread // 1.57), int(Visual().widthread // 1.36), int(Visual().widthread // 2.5),
                int(Visual().widthread // 2.02), int(Visual().widthread // 6.22), int(Visual().widthread // 3.90),
                int(Visual().heightread // 2.47)
            )

        while not self.switch:
            self.coordsofnumber(f'{datetime.now():%S}', coords[0], coords[1], coords[6])
            self.coordsofnumber(f'{datetime.now():%M}', coords[2], coords[3], coords[6])
            self.coordsofnumber(f'{datetime.now():%H}', coords[4], coords[5], coords[6])
            sleep(0.67)

    @staticmethod
    def graphicnumber(value, x, y):

        if int(value) == 0:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '██████████████')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '██████████████')

        if int(value) == 1:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '  ████████    ')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '  ██░░░░██    ')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '  ████░░██    ')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '    ██░░██    ')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '    ██░░██    ')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '    ██░░██    ')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '    ██░░██    ')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '    ██░░██    ')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '  ████░░████  ')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '  ██░░░░░░██  ')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '  ██████████  ')

        if int(value) == 2:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '██████████████')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '██░░██████████')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '██░░██        ')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '██░░██████████')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '██████████████')

        if int(value) == 3:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '██████████████')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '██████████████')

        if int(value) == 4:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '██████  ██████')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '        ██████')

        if int(value) == 5:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '██████████████')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '██░░██████████')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '██░░██        ')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '██░░██████████')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '██████████████')

        if int(value) == 6:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '██████████████')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '██░░██████████')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '██░░██        ')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '██░░██████████')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '██████████████')

        if int(value) == 7:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '██████████████')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '        ██████')

        if int(value) == 8:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '██████████████')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '██████████████')

        if int(value) == 9:
            goto(x, y)
            Visual().color.print(Visual().firstcolor + '██████████████')
            goto(x, y + 1)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 2)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 3)
            Visual().color.print(Visual().firstcolor + '██░░██  ██░░██')
            goto(x, y + 4)
            Visual().color.print(Visual().firstcolor + '██░░██████░░██')
            goto(x, y + 5)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 6)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 7)
            Visual().color.print(Visual().firstcolor + '        ██░░██')
            goto(x, y + 8)
            Visual().color.print(Visual().firstcolor + '██████████░░██')
            goto(x, y + 9)
            Visual().color.print(Visual().firstcolor + '██░░░░░░░░░░██')
            goto(x, y + 10)
            Visual().color.print(Visual().firstcolor + '██████████████')

        if Visual().widthread == 120 and Visual().heightread == 30:
            coords = (39, 79, 13, 17)
        else:
            if Visual().widthread < 237 and Visual().heightread < 66:
                coords = (int(Visual().widthread // 2.75), int(Visual().widthread // 1.66),
                          int(Visual().heightread // 2.13), int(Visual().heightread // 1.80))
            else:
                coords = (int(Visual().widthread // 2.85), int(Visual().widthread // 1.69),
                          int(Visual().heightread // 2.35), int(Visual().heightread // 1.94))

        goto(coords[0], coords[2])
        Visual().color.print(Visual().firstcolor + '██')
        goto(coords[0], coords[3])
        Visual().color.print(Visual().firstcolor + '██')
        goto(coords[1], coords[2])
        Visual().color.print(Visual().firstcolor + '██')
        goto(coords[1], coords[3])
        Visual().color.print(Visual().firstcolor + '██')
